[package]
name = "simperby-light-client"
version = "0.0.0"
authors = ["PDAO Team <hello@postech-dao.xyz>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simperby-common = { version = "0.0.0", path = "../common" }
