[workspace]
members = [
    "common",
    "node",
    "test-suite",
    "merkle-tree",
    "network",
    "kv-storage",
    "vetomint",
    "light-client",
    "cli",
    "repository",
    "consensus",
    "governance"
]