[package]
name = "vetomint"
version = "0.0.0"
authors = ["PDAO Team <hello@postech-dao.xyz>"]
edition = "2021"

[dependencies]
eyre = "0.6.8"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
thiserror = "1.0.31"
