[package]
name = "simperby-merkle-tree"
version = "0.0.0"
authors = ["PDAO Team <hello@postech-dao.xyz>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rocksdb = "0.18.0"
simperby-common = { version = "0.0.0", path = "../common" }
